apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: 
 name: frontend-egress-policy
 namespace: test
spec: 
 podSelector: 
  matchLabels: 
   run: frontend  
 policyTypes: 
 - Egress
 egress: 
 - to: 
   - podSelector: 
      matchLabels: 
       run: backend 
