apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "mtls-strict"
  namespace: "mtls"
spec:
  selector:
    matchLabels:
      app: mayank
  mtls:
    mode: STRICT
  portLevelMtls:
    80:
      mode: DISABLE
